Controllers/AuthorizationController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ExpertPlanner.Models;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

[AutoValidateAntiforgeryToken]
public class AuthorizationController : Controller
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly SignInManager<ApplicationUser> _signInManager;
    private readonly ILogger<AuthorizationController> _logger;
    private readonly IAntiforgery _antiforgery;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public AuthorizationController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager,
        ILogger<AuthorizationController> logger, IAntiforgery antiforgery, IHttpContextAccessor httpContextAccess)
    {
        _userManager = userManager;
        _signInManager = signInManager;
        _logger = logger;
        _antiforgery = antiforgery;
        _httpContextAccessor = httpContextAccess;
    }
    [AllowAnonymous]
    [HttpGet]
    public async Task<IActionResult> Auth()
    {
        bool rememberMe = Request.Cookies["RememberMe"] == "True";

        if (User.Identity.Name != null & ( User.Identity.IsAuthenticated || rememberMe) )
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            var fullName = $"{user.FirstName} {user.MiddleName}";
            _httpContextAccessor.HttpContext.Session.SetString("UserFullName", fullName);

            return RedirectToAction("Index", "Home");
        }

        return View();
    }

    [HttpPost]
    [AllowAnonymous]
    public async Task<IActionResult> Login(LoginViewModel model)
    {
        if (ModelState.IsValid)
        {
            var user = await _userManager.FindByNameAsync(model.Username);

            var cookieOptions = new CookieOptions
            {
                Secure = true,
                Expires = model.RememberMe ? DateTime.Now.AddDays(30) : DateTime.Now.AddDays(1),
                HttpOnly = true
            };
            var tokens = _antiforgery.GetAndStoreTokens(HttpContext);
            HttpContext.Session.SetString("CSRFToken", tokens.RequestToken);

            Response.Cookies.Append("MyCookieName", "MyCookieValue", cookieOptions);
            Response.Cookies.Append("RememberMe", model.RememberMe.ToString(), cookieOptions);

            if (user != null && await _userManager.CheckPasswordAsync(user, model.Password))
            {
                await _signInManager.SignInAsync(user, model.RememberMe);

                var fullName = $"{user.FirstName} {user.MiddleName}";
                _httpContextAccessor.HttpContext.Session.SetString("UserFullName", fullName);
                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError(string.Empty, "Неверный логин или пароль");
        }

        return RedirectToAction("Auth", "Authorization");
    }

    [HttpPost]
    public async Task<IActionResult> Logout()
    {
        await _signInManager.SignOutAsync();
        Response.Cookies.Delete("RememberMe");
        return RedirectToAction("Auth", "Authorization");
    }
}

Controllers/ForgotPasswordController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Razor.Compilation;

namespace ExpertPlanner.Controllers
{
    [AllowAnonymous]
    public class ForgotPasswordController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public ForgotPasswordController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult RestorePassword()
        {
            return View();
        }
    }
}

Views/Authorization/Auth.cshtml
@model ExpertPlanner.Models.LoginViewModel
@{
    ViewData["Title"] = "Auth Page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/auth_styles.css" asp-append-version="true">
    <title>Авторизация</title>
</head>
<body>

    <div class="login-container">
        <div class="logo-container">
            <img src="images/logo.png" alt="Logo" class="logo">
        </div>
        <h2 class="auth-title">Авторизация</h2>

        @using (Html.BeginForm("Login", "Authorization", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <input type="text" id="username" name="Username" required placeholder="Логин (вводить без домена)">
            <input type="password" id="password" name="Password" required placeholder="Пароль">

            <div class="remember-me">
                @Html.CheckBoxFor(model => model.RememberMe, new { id = "RememberMe" })
                <label for="RememberMe">Запомнить меня</label>
            </div>

            <button type="submit" class="enter-button">Войти</button>
        }

        @Html.ActionLink("Забыли свой пароль?", "RestorePassword", "ForgotPassword");

    </div>

</body>
</html>