Models/UserItemViewModel.cs
namespace ExpertPlanner.Models
{
    public class UserItemViewModel
    {
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Link { get; set; }
        public string Position { get; set; }
        public string Area { get; set; }
        
    }
}

Controllers/UserItemsController.cs
using Microsoft.AspNetCore.Mvc;
using ExpertPlanner.Services;
using ExpertPlanner.Models;
using System.Threading.Tasks;
using System.Collections.Generic;

public class UserItemsController : Controller
{
    private readonly DatabaseService _databaseService;

    public UserItemsController(DatabaseService databaseService)
    {
        _databaseService = databaseService;
    }

    public IActionResult UserIndex()
    {
        var tableNames = _databaseService.GetTableNames();
        return View(tableNames);
    }

    public async Task<IActionResult> Details(string tableName)
    {
        var data = await _databaseService.GetDataFromTableAsync(tableName);
        ViewBag.TableName = tableName;
        return PartialView("~/Views/UserItems/_TableDetails.cshtml", data);
    }

    [HttpPost]
    public async Task<IActionResult> SaveTable(string tableName, List<DefaultTable> model)
    {
        var tableNames = _databaseService.GetTableNames();
        if (ModelState.IsValid)
        {
            await _databaseService.UpdateDataInTableAsync(tableName, model);
        }
        return View("UserIndex", tableNames);
    }

    private string GetWeekNumber(DateTime date)
    {
        return $"{date.AddDays(-(int)date.DayOfWeek + (int)DayOfWeek.Monday):dd-MM-yyyy}";
    }
}

Views/UserItems/ViewStart.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    @RenderBody()

    @RenderSection("scripts", required: false)
</body>
</html>

Views/UserItems/_TableDetails.cshtml
@model List<DefaultTable>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>График планирования</title>
    <link rel="stylesheet" href="~/css/table_styles.css" asp-append-version="true" />
</head>

<div class="table-container">
    <form asp-controller="UserItems" asp-action="SaveTable" asp-route-tableName="@ViewBag.TableName" method="post">
    <input type="hidden" name="tableName" value="@ViewBag.TableName" />
    <div style="overflow-x:auto;">
        <table class="table">
            <thead>
                <tr>
                    <th>ФИО</th>
                    <th>Telegram</th>
                    <th>Должность</th>
                    <th>Пн</th>
                    <th>Вт</th>
                    <th>Ср</th>
                    <th>Чт</th>
                    <th>Пт</th>
                    <th>Сб</th>
                    <th>Вс</th>
                </tr>
            </thead>
            <tbody>
                @for (var i = 0; i < Model.Count; i++)
                {
                        <tr>
                            <td>
                                <div class="input-container">
                                    <input type="text" asp-for="@Model[i].LastName" placeholder="Фамилия" />
                                    <input type="text" asp-for="@Model[i].FirstName" placeholder="Имя" />
                                    <input type="text" asp-for="@Model[i].MiddleName" placeholder="Отчество" />
                                    <input type="hidden" asp-for="@Model[i].Id" />
                                </div>
                            </td>
                            <td><div class="input-container"><input type="text" asp-for="@Model[i].Link" /></div></td>
                            <td><div class="input-container"><input type="text" asp-for="@Model[i].Position" /></div></td>
                            <td><div class="input-container"><input type="text" asp-for="@Model[i].Monday" /></div></td>
                            <td><div class="input-container"><input type="text" asp-for="@Model[i].Tuesday" /></div></td>
                            <td><div class="input-container"><input type="text" asp-for="@Model[i].Wednesday" /></div></td>
                            <td><div class="input-container"><input type="text" asp-for="@Model[i].Thursday" /></div></td>
                            <td><div class="input-container"><input type="text" asp-for="@Model[i].Friday" /></div></td>
                            <td><div class="input-container"><input type="text" asp-for="@Model[i].Saturday" /></div></td>
                            <td><div class="input-container"><input type="text" asp-for="@Model[i].Sunday" /></div></td>
                        </tr>
                }
            </tbody>
        </table>
    </div>
        <div class="btns-container">
            <button class="btn" type="submit">Сохранить</button>
        </div>
</form>
</div>